### ISSUE TITLE
Don''t clear text on device rotation

### ISSUE THREAD

**Issue by licaon-kter** [SCOTT-HAMILTON/Trollslate#1]
https://github.com/SCOTT-HAMILTON/Trollslate/commit/aa716799de1b2088143151a2d5be96d93ce2e929

**Comment by SCOTT-HAMILTON** [comment]
Sorry but I'm not sure to understand what's the issue, maybe I somewhat fixed it while working on the other issues.

Becaus when I write some text on the trollTextField and then change the phoneAngle, the textField still keeps its content.

**Comment by licaon-kter** [comment]
Did you change the angle with 90°?


From portrait to landscape...

**Comment by licaon-kter** [comment]
Still an issue on Delacroix
