### ISSUE TITLE
Back gesture should not exit app when looking at text

### ISSUE THREAD

**Issue by licaon-kter** [SCOTT-HAMILTON/Trollslate#2]
https://github.com/SCOTT-HAMILTON/Trollslate/commit/aa716799de1b2088143151a2d5be96d93ce2e929

**Comment by SCOTT-HAMILTON** [comment]
Fixed by using the navController instead of launching a new activity cf 6f0587a0ba0a11c50c8139d5b2696fd0f715c3a7.

**Comment by licaon-kter** [comment]
Reopen this, now back gestures does not do anything, you're stuck in the app ;(
