### ISSUE TITLE
App can no longer render text if ENTER is pressed

### ISSUE THREAD

**Issue by licaon-kter** [SCOTT-HAMILTON/Trollslate#3]
https://github.com/SCOTT-HAMILTON/Trollslate/commit/aa716799de1b2088143151a2d5be96d93ce2e929

Write text
Press ENTER
Write text
Press ENTER
Write text
Press ENTER
Write text
Press ENTER
...
Press the render button

**Comment by SCOTT-HAMILTON** [comment]
Fixed https://github.com/SCOTT-HAMILTON/Trollslate/commit/7309eb60032cf143ffe45e00d909b1c809f50e18 ?

**Comment by licaon-kter** [comment]
thanks
