### ISSUE TITLE
Rotation does not change anything

### ISSUE THREAD

**Issue by licaon-kter** [SCOTT-HAMILTON/Trollslate#4]
https://github.com/SCOTT-HAMILTON/Trollslate/commit/aa716799de1b2088143151a2d5be96d93ce2e929

**Comment by SCOTT-HAMILTON** [comment]
It does change the size ratio of the letters once the troll activity is launched.

The more little the angle the harder it is to read.

**Comment by licaon-kter** [comment]
It makes them longer I see, mmakay
