### ISSUE TITLE
License Text

### ISSUE THREAD

**Issue by the7thNightmare** [SCOTT-HAMILTON/Trollslate#7]
Currently the only indicator of the license is in the README.md, but it is best to include the license text in the root directory by adding a file named `LICENSE` and adding the MIT Expat text to there. The MIT Expat License text are in https://opensource.org/licenses/MIT.

**Comment by SCOTT-HAMILTON** [comment]
Fixed by https://github.com/SCOTT-HAMILTON/Trollslate/commit/734523f251830b53ad74f93e8c6e76508ea35f22, thanks !
